export const REQUESET_FOR_GET_USER:string = "REQUESET_FOR_GET_USER"

export const GET_USER_SUCCESSFULLY:string = "GET_USER_SUCCESSFULLY"

export const USER_REQUEST_UNSUCCESSFULLY:string = "USER_REQUEST_UNSUCCESSFULLY"